### ISSUE TITLE
BUG: crypto.randomUUID is not a function

### ISSUE THREAD

**Issue by jurelou** [center-for-threat-informed-defense/attack-flow#54]
Hi,

Using the latest version (commit `a3800be134c07d8aa281b85fa6d83df3121c3446`) I have the following error:

```js
Uncaught TypeError: crypto.randomUUID is not a function
    at new n (DiagramObjectModel.ts:98:49)
    at new y (DiagramRootModel.ts:37:9)
    at new S (PageModel.ts:48:9)
    at S.createDummy (PageModel.ts:65:16)
    at L.createDummy (PageEditor.ts:104:43)
    at Module.cd49 (ApplicationStore.ts:13:30)
    at l (bootstrap:89:22)
    at 0 (app.63248f86.js:1:3257)
    at l (bootstrap:89:22)
    at i (bootstrap:45:15)
```

I am deploying attack-flow via the provided dockerfile.

Also, are you going to publish stables docker images on dockerhub ?

Thanks

**Comment by tubetrain** [comment]
I'm also experiencing this problem. No GUI elements load, just a black screen. Same error message

**Comment by jurelou** [comment]
> Thanks, we will look into this and will also publish stable docker images.

I god the bug on chrome and firefox
